service: serverless-api-typescript-boilerplate
frameworkVersion: '3'
variablesResolutionMode: 20210326
configValidationMode: warn

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  eventBridge:
    useCloudFormation: true
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION, 'us-east-1'}
  stackName: ${self:provider.stage}-${self:service}
  logRetentionInDays: 30
  runtime: nodejs14.x
  timeout: 20 # seconds
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
            - kms:Describe*
            - kms:Encrypt*
            - kms:Decrypt*
            - kms:GenerateDataKey
          Resource: '*'
        - Effect: Allow
          Action:
            - ssm:GetParametersByPath
          Resource:
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter${self:provider.environment.SSM_APP_PATH}
  environment: ${self:custom.environment.${self:provider.stage}}

package:
  individually: true

custom:
  defaultEnvVars: &defaultEnvVars
    APP_NAME: ${self:service}
    SSM_APP_PATH: /app/${self:provider.stage}/${self:service}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    STAGE: ${self:provider.stage}
  environment:
    dev:
      <<: *defaultEnvVars
      AWS_DYNAMODB_TABLE: ${self:service}
      AWS_DYNAMODB_ENDPOINT: http://0.0.0.0:4566
    prod:
      <<: *defaultEnvVars
      AWS_DYNAMODB_TABLE:
        Ref: Table
  serverless-offline:
    host: 0.0.0.0
    httpPort: ${env:PORT, 5000}
    noPrependStageInUrl: true
  webpack: # read by serverless-webpack
    webpackConfig: ./webpack.config.js
    packager: npm
    includeModules: true # not sure why webpack-node-externals is not doing this
  customDomain:
    apiType: http
    domainName: ${ssm:/deploy/${self:service}/DOMAIN_NAME, ''}
    stage: ${self:provider.stage}
    basePath: ''
    certificateArn: ${ssm:/deploy/${self:service}/ACM_CERTIFICATE, ''}
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    autoDomain: true

functions:
  api:
    handler: src/index.api
    events:
      - httpApi: '*'

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        Tags:
          - Key: Name
            Value: ${self:service}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
        # PointInTimeRecoverySpecification:
        #   PointInTimeRecoveryEnabled: true

    WriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
        MaxCapacity: 100
        MinCapacity: 1
        ResourceId:
          Fn::Join:
            - /
            - - table
              - !Ref Table
        RoleARN:
          Fn::GetAtt:
            - ScalingRole
            - Arn
        ScalableDimension: dynamodb:table:WriteCapacityUnits
        ServiceNamespace: dynamodb

    ReadCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
        MaxCapacity: 100
        MinCapacity: 1
        ResourceId:
          Fn::Join:
            - /
            - - table
              - !Ref Table
        RoleARN:
          Fn::GetAtt:
            - ScalingRole
            - Arn
        ScalableDimension: dynamodb:table:ReadCapacityUnits
        ServiceNamespace: dynamodb

    ScalingRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - application-autoscaling.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: '/'
        Policies:
          -
            PolicyName:
              Fn::Join:
                - '-'
                - - !Ref Table
                  - scaling-role
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:UpdateTable
                    - cloudwatch:PutMetricAlarm
                    - cloudwatch:DescribeAlarms
                    - cloudwatch:GetMetricStatistics
                    - cloudwatch:SetAlarmState
                    - cloudwatch:DeleteAlarms
                  Resource: '*'

    WriteScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      Properties:
        PolicyName: WriteAutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId:
          Ref: WriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
          TargetValue: 30.0
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification:
            PredefinedMetricType: DynamoDBWriteCapacityUtilization

    ReadScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      Properties:
        PolicyName: ReadutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId:
          Ref: ReadCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
          TargetValue: 30.0
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification:
            PredefinedMetricType: DynamoDBReadCapacityUtilization
